const colors = {
  light: {
    text: "#ffffff",
    tint: "#4dd45a",
    background: "#0e90b7",
    foreground: "#ffffff",
    card: "#0b7ea0",
    cardForeground: "#ffffff",
    primary: "#4dd45a",
    primaryForeground: "#ffffff",
    secondary: "#3d9eff",
    secondaryForeground: "#ffffff",
    muted: "#0d7a9e",
    mutedForeground: "#a0d4e8",
    accent: "#ffc107",
    accentForeground: "#ffffff",
    destructive: "#ff3d3d",
    destructiveForeground: "#ffffff",
    border: "#1aa3c5",
    input: "#1aa3c5",
    purple: "#9b5fd4",
    purpleDark: "#7a3fb5",
    gold: "#ffc107",
    coin: "#ff9500",
    gem: "#00d4ff",
    green: "#4dd45a",
    greenDark: "#2db53e",
    headerBg: "#0a7ca0",
    tabBg: "#0a7ca0",
    chestBg: "#083d5a",
    cream: "#f5e6c8",
    saleRed: "#ff3030",
    badgeOrange: "#ff7a00",
  },
  radius: 12,
};

export default colors;
